/* eslint-disable @next/next/no-img-element */
import { AdminHeader } from "@/components/admin/AdminHeader";
import { ProfileContentNav } from "@/components/admin/ProfileContentNav";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { notFound } from "next/navigation";
import { deleteEventAction, toggleEventVisibleAction } from "../content-actions";

type PageProps = { params: Promise<{ id: string }> };
export default async function AdminProfileEventsPage({ params }: PageProps) { const { id } = await params; const profile = await prisma.profile.findUnique({ where: { id }, select: { id: true, displayName: true, slug: true } }); if (!profile) notFound(); const events = await prisma.profileEvent.findMany({ where: { profileId: profile.id }, orderBy: [{ startDate: "asc" }, { sortOrder: "asc" }] }); return <div><AdminHeader eyebrow="Evenements" title={profile.displayName} description={`Evenements affiches sur /${profile.slug}.`} action={{ href: `/admin/profiles/${profile.id}/events/new`, label: "Ajouter un evenement" }} /><ProfileContentNav profileId={profile.id} active="events" /><section className="mt-6 overflow-hidden rounded-lg border border-aodi-violet-100 bg-[#FBF8F1]/90 shadow-sm">{events.length === 0 ? <div className="p-6"><p className="text-sm text-aodi-violet-700/70">Aucun evenement pour le moment.</p><Link href={`/admin/profiles/${profile.id}/events/new`} className="mt-4 inline-flex rounded-lg bg-aodi-violet-900 px-4 py-2 text-sm font-semibold text-white">Ajouter un evenement</Link></div> : events.map((event) => <article key={event.id} className="grid gap-4 border-b border-aodi-violet-100 p-5 lg:grid-cols-[80px_1fr_120px] lg:items-center"><div className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-lg bg-aodi-violet-950/10 text-[10px] font-bold uppercase text-aodi-violet-700/45">{event.imageUrl ? <img src={event.imageUrl} alt={event.title} className="h-full w-full object-cover" /> : <span>{new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "short" }).format(event.startDate)}</span>}</div><div><p className="font-semibold text-aodi-violet-900">{event.title}</p><p className="mt-1 text-sm text-aodi-violet-700/70">{event.location ?? "Lieu non renseigne"}</p><p className="mt-1 text-xs text-aodi-violet-700/60">{event.isVisible ? "Visible" : "Masque"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/profiles/${profile.id}/events/${event.id}/edit`} className="rounded-lg border border-aodi-violet-200 bg-white px-3 py-2 text-xs font-semibold">Modifier</Link><form action={toggleEventVisibleAction.bind(null, profile.id, event.id)}><button className="rounded-lg border border-aodi-violet-200 bg-white px-3 py-2 text-xs font-semibold">{event.isVisible ? "Masquer" : "Afficher"}</button></form><form action={deleteEventAction.bind(null, profile.id, event.id)}><button className="rounded-lg border border-red-200 bg-white px-3 py-2 text-xs font-semibold text-red-700">Supprimer</button></form></div></article>)}</section></div>; }