/* eslint-disable @next/next/no-img-element */
import { AdminHeader } from "@/components/admin/AdminHeader";
import { ProfileContentNav } from "@/components/admin/ProfileContentNav";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { notFound } from "next/navigation";
import { deleteProjectAction, toggleProjectFeaturedAction, toggleProjectVisibleAction } from "../content-actions";

type PageProps = { params: Promise<{ id: string }> };

export default async function AdminProfileProjectsPage({ params }: PageProps) {
  const { id } = await params;
  const profile = await prisma.profile.findUnique({ where: { id }, select: { id: true, displayName: true, slug: true } });
  if (!profile) notFound();
  const projects = await prisma.project.findMany({ where: { profileId: profile.id }, orderBy: [{ displayOrder: "asc" }, { createdAt: "desc" }] });
  return <div><AdminHeader eyebrow="Projets" title={profile.displayName} description={`Realisations affichees sur /${profile.slug}.`} action={{ href: `/admin/profiles/${profile.id}/projects/new`, label: "Ajouter un projet" }} /><ProfileContentNav profileId={profile.id} active="Projets" /><section className="mt-6 overflow-hidden rounded-lg border border-aodi-violet-100 bg-[#FBF8F1]/90 shadow-sm">{projects.length === 0 ? <div className="p-6"><p className="text-sm text-aodi-violet-700/70">Aucun projet pour ce profil.</p><Link href={`/admin/profiles/${profile.id}/projects/new`} className="mt-4 inline-flex rounded-lg bg-aodi-violet-900 px-4 py-2 text-sm font-semibold text-white">Ajouter le premier projet</Link></div> : projects.map((project) => <article key={project.id} className="grid gap-4 border-b border-aodi-violet-100 p-5 lg:grid-cols-[80px_1fr_160px] lg:items-center"><div className="h-16 w-16 overflow-hidden rounded-lg bg-aodi-violet-950/10">{project.imageUrl ? <img src={project.imageUrl} alt={project.title} className="h-full w-full object-cover" /> : null}</div><div><p className="font-semibold text-aodi-violet-900">{project.title}</p><p className="mt-1 text-sm text-aodi-violet-700/70">{project.technologies || "Technologies non renseignees"}</p><p className="mt-1 text-xs text-aodi-violet-700/60">Ordre {project.displayOrder} - {project.isVisible ? "Visible" : "Masque"} - {project.isFeatured ? "En avant" : "Standard"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/profiles/${profile.id}/projects/${project.id}/edit`} className="rounded-lg border border-aodi-violet-200 bg-white px-3 py-2 text-xs font-semibold">Modifier</Link><form action={toggleProjectVisibleAction.bind(null, profile.id, project.id)}><button className="rounded-lg border border-aodi-violet-200 bg-white px-3 py-2 text-xs font-semibold">{project.isVisible ? "Masquer" : "Afficher"}</button></form><form action={toggleProjectFeaturedAction.bind(null, profile.id, project.id)}><button className="rounded-lg border border-aodi-violet-200 bg-white px-3 py-2 text-xs font-semibold">{project.isFeatured ? "Retirer" : "En avant"}</button></form><form action={deleteProjectAction.bind(null, profile.id, project.id)}><button className="rounded-lg border border-red-200 bg-white px-3 py-2 text-xs font-semibold text-red-700">Supprimer</button></form></div></article>)}</section></div>;
}